Update Jenkinsfile

diff --git a/MERN-Stack-Ecommerce-App-master/Jenkinsfile b/MERN-Stack-Ecommerce-App-master/Jenkinsfile
--- a/MERN-Stack-Ecommerce-App-master/Jenkinsfile
+++ b/MERN-Stack-Ecommerce-App-master/Jenkinsfile
@@ -29,15 +29,24 @@ pipeline {
         }
 
         stage('Build Frontend App') {
-            steps {
-                dir('MERN-Stack-Ecommerce-App-master') {
-                    sh '''
-                    npm install
-                    CI=false npm run build
-                    '''
-                }
-            }
+    steps {
+        dir('MERN-Stack-Ecommerce-App-master') {
+            sh '''
+            echo "==== WHO AM I ===="
+            whoami
+            echo "==== PATH ===="
+            echo $PATH
+            echo "==== NODE ===="
+            which node || echo "node NOT found"
+            echo "==== NPM ===="
+            which npm || echo "npm NOT found"
+
+            npm install
+            CI=false npm run build
+            '''
         }
+    }
+}
 
         stage('Build Frontend Docker Image') {
             steps {
